/*
var maxBuildingLevels = {
    headquarter: 30,
    barracks: 25,
    tavern: 15,
    hospital: 10,
    preceptory: 10,
    church: 3,
    chapel: 1,
    academy: 1,
    rally_point: 5,
    statue: 5,
    market: 25,
    timber_camp: 30,
    clay_pit: 30,
    iron_mine: 30,
    farm: 30,
    warehouse: 30,
    wall: 20
};

var initialBuildingLevels = {
    headquarter: 2,
    barracks: 1,
    tavern: 0,
    hospital: 0,
    preceptory: 0,
    church: 0,
    chapel: 1,
    academy: 0,
    rally_point: 1,
    statue: 0,
    market: 0,
    timber_camp: 0,
    clay_pit: 0,
    iron_mine: 0,
    farm: 1,
    warehouse: 1,
    wall: 0
};

var buildings = {
    academy: 'academy',
    barracks: 'barracks',
    chapel: 'chapel',
    church: 'church',
    clay_pit: 'clay_pit',
    farm: 'farm',
    headquarter: 'headquarter',
    hospital: 'hospital',
    iron_mine: 'iron_mine',
    market: 'market',
    preceptory: 'preceptory',
    rally_point: 'rally_point',
    statue: 'statue',
    tavern: 'tavern',
    timber_camp: 'timber_camp',
    wall: 'wall',
    warehouse: 'warehouse'
};
*/

var optimalBuildQueue = [
    // Day 1
    buildings.headquarter,
    buildings.headquarter,
    buildings.headquarter,
    buildings.timber_camp,
    buildings.timber_camp,
    buildings.clay_pit,
    buildings.timber_camp,
    buildings.clay_pit,
    buildings.farm,
    buildings.iron_mine,
    buildings.warehouse,
    buildings.iron_mine,
    buildings.timber_camp,
    buildings.farm,
    buildings.clay_pit,

    // Day 2
    buildings.timber_camp,
    buildings.iron_mine,
    buildings.clay_pit,
    buildings.farm,
    buildings.timber_camp,
    buildings.iron_mine,
    buildings.timber_camp,
    buildings.warehouse,
    buildings.clay_pit,
    buildings.statue,
    buildings.warehouse,
    buildings.farm,
    buildings.barracks,
    buildings.iron_mine,
    buildings.barracks,

    // Day 3
    buildings.barracks,
    buildings.iron_mine,
    buildings.barracks,
    buildings.clay_pit,
    buildings.headquarter,
    buildings.market,
    buildings.headquarter,
    buildings.wall,
    buildings.headquarter,
    buildings.tavern,
    buildings.clay_pit,
    buildings.rally_point,
    buildings.warehouse,
    buildings.farm,
    buildings.iron_mine,

    // Day 4
    buildings.barracks,
    buildings.timber_camp,
    buildings.barracks,
    buildings.headquarter,
    buildings.iron_mine,
    buildings.timber_camp,
    buildings.warehouse,
    buildings.headquarter,
    buildings.market,
    buildings.barracks,
    buildings.wall,
    buildings.barracks,
    buildings.tavern,
    buildings.headquarter,
    buildings.warehouse,

    // Day 5
    buildings.barracks,
    buildings.timber_camp,
    buildings.barracks,
    buildings.farm,
    buildings.hospital,
    buildings.timber_camp,
    buildings.warehouse,
    buildings.headquarter,
    buildings.iron_mine,
    buildings.barracks,
    buildings.wall,
    buildings.clay_pit,
    buildings.market,
    buildings.clay_pit,
    buildings.wall,

    // Day 6
    buildings.iron_mine,
    buildings.market,
    buildings.timber_camp,
    buildings.iron_mine,
    buildings.farm,
    buildings.clay_pit,
    buildings.warehouse,
    buildings.headquarter,
    buildings.iron_mine,
    buildings.clay_pit,
    buildings.wall,
    buildings.clay_pit,
    buildings.tavern,
    buildings.clay_pit,
    buildings.warehouse,

    // Day 7
    buildings.timber_camp,
    buildings.market,
    buildings.timber_camp,
    buildings.iron_mine,
    buildings.farm,
    buildings.clay_pit,
    buildings.warehouse,
    buildings.clay_pit,
    buildings.wall,
    buildings.timber_camp,
    buildings.iron_mine,
    buildings.farm,
    buildings.tavern,
    buildings.iron_mine,
    buildings.warehouse,

    // Day 8
    buildings.timber_camp,
    buildings.farm,
    buildings.iron_mine,
    buildings.rally_point,
    buildings.clay_pit,
    buildings.warehouse,
    buildings.farm,
    buildings.clay_pit,
    buildings.wall,
    buildings.timber_camp,
    buildings.farm,
    buildings.iron_mine,
    buildings.tavern,
    buildings.hospital,
    buildings.warehouse,

    // Day 9
    buildings.barracks,
    buildings.farm,
    buildings.barracks,
    buildings.headquarter,
    buildings.statue,
    buildings.headquarter,
    buildings.wall,
    buildings.market,
    buildings.barracks,
    buildings.hospital,
    buildings.barracks,
    buildings.wall,
    buildings.headquarter,
    buildings.wall,
    buildings.headquarter,

    // Day 10
    buildings.barracks,
    buildings.farm,
    buildings.barracks,
    buildings.timber_camp,
    buildings.headquarter,
    buildings.wall,
    buildings.clay_pit,
    buildings.tavern,
    buildings.barracks,
    buildings.iron_mine,
    buildings.barracks,
    buildings.warehouse,
    buildings.headquarter,
    buildings.wall,
    buildings.headquarter,

    // Day 11
    buildings.wall,
    buildings.timber_camp,
    buildings.market,
    buildings.timber_camp,
    buildings.rally_point,
    buildings.clay_pit,
    buildings.wall,
    buildings.academy,
    buildings.market,
    buildings.hospital,
    buildings.iron_mine,
    buildings.wall,
    buildings.clay_pit,
    buildings.hospital,
    buildings.statue,

    // Day 12
    buildings.warehouse,
    buildings.timber_camp,
    buildings.market,
    buildings.timber_camp,
    buildings.market,
    buildings.clay_pit,
    buildings.tavern,
    buildings.iron_mine,
    buildings.farm,
    buildings.clay_pit,
    buildings.tavern,
    buildings.iron_mine,
    buildings.market,
    buildings.timber_camp,
    buildings.clay_pit,

    // Day 13
    buildings.warehouse,
    buildings.iron_mine,
    buildings.farm,
    buildings.timber_camp,
    buildings.warehouse,
    buildings.iron_mine,
    buildings.farm,
    buildings.clay_pit,
    buildings.warehouse,
    buildings.iron_mine,
    buildings.farm,
    buildings.timber_camp,
    buildings.warehouse,
    buildings.clay_pit,
    buildings.farm,

    // Day 14
    buildings.iron_mine,
    buildings.market,
    buildings.timber_camp,
    buildings.tavern,
    buildings.timber_camp,
    buildings.market,
    buildings.clay_pit,
    buildings.market,
    buildings.iron_mine,
    buildings.market,
    buildings.clay_pit,
    buildings.rally_point,
    buildings.iron_mine,
    buildings.statue,
    buildings.timber_camp,

    // Day 15
    buildings.statue,
    buildings.timber_camp,
    buildings.market,
    buildings.timber_camp,
    buildings.market,
    buildings.clay_pit,
    buildings.market,
    buildings.iron_mine,
    buildings.market,
    buildings.clay_pit,
    buildings.market,
    buildings.iron_mine,
    buildings.farm,
    buildings.clay_pit,
    buildings.iron_mine,

    // Day 16
    buildings.tavern,
    buildings.headquarter,
    buildings.warehouse,
    buildings.barracks,
    buildings.farm,
    buildings.headquarter,
    buildings.warehouse,
    buildings.barracks,
    buildings.farm,
    buildings.headquarter,
    buildings.warehouse,
    buildings.barracks,
    buildings.farm,
    buildings.headquarter,
    buildings.warehouse,

    // Day 17
    buildings.headquarter,
    buildings.warehouse,
    buildings.preceptory,
    buildings.farm,
    buildings.headquarter,
    buildings.hospital,
    buildings.barracks,
    buildings.headquarter,
    buildings.barracks,
    buildings.tavern,
    buildings.headquarter,
    buildings.tavern,
    buildings.headquarter,
    buildings.tavern,
    buildings.headquarter,

    // Day 18
    buildings.hospital,
    buildings.tavern,
    buildings.preceptory,
    buildings.hospital,
    buildings.tavern,
    buildings.warehouse,
    buildings.farm,
    buildings.warehouse,
    buildings.preceptory,
    buildings.farm,
    buildings.warehouse,
    buildings.preceptory,
    buildings.farm,
    buildings.warehouse,
    buildings.preceptory,

    // Day 19
    buildings.warehouse,
    buildings.hospital,
    buildings.farm,
    buildings.preceptory,
    buildings.wall,
    buildings.market,
    buildings.wall,
    buildings.preceptory,
    buildings.wall,
    buildings.market,
    buildings.farm,
    buildings.market,
    buildings.wall,
    buildings.preceptory,
    buildings.wall,

    // Day 20
    buildings.hospital,
    buildings.preceptory,
    buildings.market,
    buildings.market,
    buildings.preceptory
];

/*
for (var i=0; i<optimalBuildQueue.length; i++) {
    var key = optimalBuildQueue[i];
    initialBuildingLevels[key]++;
}

var str = "\n";

for (var key in initialBuildingLevels) {
    str += ("            " + key).slice(-12) + '\t' + initialBuildingLevels[key] + '\t(' + maxBuildingLevels[key] + ')' +
    '\t' + (initialBuildingLevels[key] - maxBuildingLevels[key]) + '\n';
}

str
*/